### ISSUE TITLE
bug: server error

### ISSUE THREAD

**Issue by Shivakumar133** [JioTV-Go/jiotv_go#451]
### Bug description

After installing & try to run jio tv go ,it shows after 5/5 attempts server error , I have been tried many times but not fixed till now 
![IMG_20241006_073048](https://github.com/user-attachments/assets/2a36a3f7-20ff-4a40-9df8-842a4010cae0)

### Steps to reproduce

....

### Relevant log output

```shell
...
```

### Screenshots or videos

![IMG_20241006_073048](https://github.com/user-attachments/assets/f0aedebb-36cf-435b-9190-302be4a683a2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
This is related to CustTermux and not JioTV Go
Stop spamming here
