### ISSUE TITLE
bug: gzip: invalid header

### ISSUE THREAD

**Issue by rocksolid2018** [JioTV-Go/jiotv_go#452]
### Bug description

Getting error in the latest docker image. Container goes into restart continuously   

 │                     JioTV Go                      │ 
 │                   Fiber v2.52.5                   │ 
 │               http://127.0.0.1:5001               │ 
 │       (bound on host 0.0.0.0 and port 5001)       │ 
 │ Handlers ............ 48  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ................. 1 │ 
[DEBUG] 2024/10/06 15:06:24 auth.go:290: Checking if SSOToken is expired...
[DEBUG] 2024/10/06 15:06:24 scheduler.go:40: Task added with ID: jiotv_refresh_sso_token
[DEBUG] 2024/10/06 15:06:24 auth.go:302: Refreshing SSOToken after 21h54m57s
[DEBUG] 2024/10/06 15:06:25 auth.go:175: gzip: invalid header

### Steps to reproduce

removed all files and install docker image from scratch same issue. Sometime, it works for an hour and then same error. 

### Relevant log output

```shell
│                     JioTV Go                      │ 
 │                   Fiber v2.52.5                   │ 
 │               http://127.0.0.1:5001               │ 
 │       (bound on host 0.0.0.0 and port 5001)       │ 
 │ Handlers ............ 48  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ................. 1 │ 
[DEBUG] 2024/10/06 15:06:24 auth.go:290: Checking if SSOToken is expired...
[DEBUG] 2024/10/06 15:06:24 scheduler.go:40: Task added with ID: jiotv_refresh_sso_token
[DEBUG] 2024/10/06 15:06:24 auth.go:302: Refreshing SSOToken after 21h54m57s
[DEBUG] 2024/10/06 15:06:25 auth.go:175: gzip: invalid header
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by itsyourap** [comment]
I believe you haven't updated your docker image to `ghcr.io/jiotv-go/jiotv_go`
Old docker image will no longer be updated.

**Comment by rocksolid2018** [comment]
changing the image seems to have addressed the issue, Will observe and report otherwise
