### ISSUE TITLE
bug: Unable to login

### ISSUE THREAD

**Issue by jckefan** [JioTV-Go/jiotv_go#455]
### Bug description

Let me preface this by saying that I have tried x86 Windows machine as well Raspberry Pi with multiple phone number all related to JIO. However, every time, the login process fails with ```request failed with status code: 400 body: {"code":1002,"message":"Please login with a Jio phone number"}```

I have tried the latest v3.11 as well as the current dev version both have failed. 

### Steps to reproduce

1. Download the JioTV Go executable.
2. Try logging in with ```jiotv_go-linux-arm login otp```
3. The login process fails.

### Relevant log output

```shell
[DEBUG] 2024/10/13 17:19:35 epg.go:181: Fetched 1062 channels
   0% |                                                                                                                                               | (0/1062, 0 it/hr) [0s:0s][DEBUG] 2024/10/13 17:19:35 epg.go:191: Fetching EPG for channels
  27% |██████████████████████████████████████                                                                                                       | (287/1062, 94 it/s) [3s:8s][DEBUG] 2024/10/13 17:19:39 epg.go:139: Error unmarshaling EPG response for channel 779, offset 0: invalid character 'P' looking for beginning of value
[DEBUG] 2024/10/13 17:19:39 epg.go:141: Response body: Params Incorrect
 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1062/1062, 88 it/s)
[DEBUG] 2024/10/13 17:19:48 epg.go:208: Fetched programmes
[DEBUG] 2024/10/13 17:19:52 epg.go:244: Writing XML to gzip file
        EPG file generated successfully
[DEBUG] 2024/10/13 17:19:56 epg.go:80: Scheduled EPG generation on 2024-10-14 02:55:00 +0530 IST
[DEBUG] 2024/10/13 17:19:56 scheduler.go:40: Task added with ID: jiotv_epg
[DEBUG] 2024/10/13 17:20:35 utils.go:454: key not found: ssoToken
[DEBUG] 2024/10/13 17:20:52 auth.go:37: request failed with status code: 400 body: {"code":1002,"message":"Please login with a Jio phone number"}
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
Can you try logging in jio.com with those numbers and see if it's successful

**Comment by jckefan** [comment]
> Can you try logging in JioTV app with those numbers and see if it's successful

Hi, thanks for the quick response. I have used one of my numbers to login to JioTV app on Android TV, and it works fine.

**Comment by rabilrbl** [comment]
Since when JioTV App is on Android TV?

**Comment by rabilrbl** [comment]
For clarity, this should be the app
https://play.google.com/store/apps/details?id=com.jio.jioplay.tv

**Comment by jckefan** [comment]
> For clarity, this should be the app and you should try in mobile
> 
> https://play.google.com/store/apps/details?id=com.jio.jioplay.tv

This is for mobile. This one works on Android TV:

https://play.google.com/store/apps/details?id=com.jio.media.jiotvplus&hl=en_IN

**Comment by jckefan** [comment]
Okay, I achieved success. Basically I tried another JIO number this time, and it worked.

**Comment by jckefan** [comment]
I believe the current implementation only supports JioTV, not JioTV+. Apparently they both are different services. The numbers I was trying before are all related to Jio Airfiber which only supports JioTV+ not JioTV.

**Comment by rabilrbl** [comment]
Yes only JioTV Mobile and not JioTV+
