### ISSUE TITLE
bug: OTP isn't coming from past week.

### ISSUE THREAD

**Issue by Dhruvpatel2112** [JioTV-Go/jiotv_go#458]
### Bug description

I've tried 3 different Jio numbers but otp stopped coming over the past week. pls fix ASAP

### Steps to reproduce

go to login section. add jio number but otp isn't coming. i've tried to reinstall jio tv go apk but otp isn't coming.

### Relevant log output

```shell
no otp coming.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
If you are talking about CustTermux JioTV Go. We don't provide support here

**Comment by Dhruvpatel2112** [comment]
Reported bug there thanks for your response
