### ISSUE TITLE
feat: Categorie wise `tvg-id` update and sort query for IPTV api

### ISSUE THREAD

**Issue by clitic** [JioTV-Go/jiotv_go#469]
### Feature description

Hey, I am using [this api](https://jiotv_go.rabil.me/usage/paths.html#m3u-playlist-alias) to fetch playlist to [SparkleTV](https://play.google.com/store/apps/details?id=se.hedekonsult.sparkle). There are several query parameters to tweak but I am interested in sorting channels in categorie wise and updating there `tvg-id` according to it.

### Solution

So the sorting mechanism should look like this.

```
English
  Entertainment
  Kids
  ...
Hindi
  Entertainment
  Kids
  ...
...
```

This should also update `tvg-id` value of each channel. A query parameter something like `update=true` can be used.

This would make much more easier to remember channels number rather than an unorganised indexing.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
We can't go with this idea. Channel ids are served directly from the JioTV API. Going with this idea will create inconsistencies whenever Jio adds a new channel. 

To keep things simple enough and easy to maintain this project in the long term, I'm closing this issue.
