### ISSUE TITLE
feat: TATA play GO

### ISSUE THREAD

**Issue by nitinjs** [JioTV-Go/jiotv_go#473]
### Feature description

requesting https://watch.tataplay.com playlist automation

### Solution

generate jiotv go like interface for https://watch.tataplay.com

### Additional context

https://watch.tataplay.com allows watching subscribed channels in web interface, I wonder if JIO TV GO like playlist support can be added

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by itsyourap** [comment]
JioTV Go is designed only for JioTV and will contain channels available in JioTV only.
