### ISSUE TITLE
feat: please add zee channels 

### ISSUE THREAD

**Issue by Manguman69** [JioTV-Go/jiotv_go#490]
### Feature description

there are only zee news channels no entertainment and no movie channels of zee

please add it

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by itsyourap** [comment]
Duplicate of #464
